api:
  version: "v1"
  prefix: "/api/{api_version}"
  routes:
    utils:
      _tags: ["Utils"]
      ping: "/ping" # GET
      health: "/health" # GET
    tasks:
      _tags: ["Tasks"]
      _prefix: "/tasks" # GET, POST
      task: "/{task_id}" # GET, PUT, DELETE
