env: local
debug: false

app:
  name: "{{cookiecutter.project_name}}"
  bind_host: "0.0.0.0"
  port: 8000
  tz: "{{cookiecutter.timezone}}"
  api_version: "v1"
  api_prefix: "/api/{api_version}"
  behind_proxy: true
  behind_cf_proxy: true
  gzip_min_size: 1024 # Bytes (1KB)
  data_dir: "/var/lib/{{cookiecutter.project_slug}}"
