db:
  dialect: "postgresql"
  driver: "psycopg"
  host: "localhost"
  port: 5432
  username: "{{cookiecutter.project_abbr}}_user"
  password: "{{cookiecutter.project_abbr}}_password1"
  database: "{{cookiecutter.project_abbr}}_db"
  # dsn_url: "postgresql+psycopg://{{cookiecutter.project_abbr}}_user:{{cookiecutter.project_abbr}}_password1@localhost:5432/{{cookiecutter.project_abbr}}_db"
  # read_host: "localhost"
  # read_port: 5432
  # read_username: "{{cookiecutter.project_abbr}}_user"
  # read_password: "{{cookiecutter.project_abbr}}_password1"
  # read_database: "{{cookiecutter.project_abbr}}_db"
  # read_dsn_url: "postgresql+psycopg://{{cookiecutter.project_abbr}}_user:{{cookiecutter.project_abbr}}_password1@localhost:5432/{{cookiecutter.project_abbr}}_db"
  table_prefix: "{{cookiecutter.project_abbr}}_"
  max_try_connect: 3
  wait_seconds_try_connect: 5
  echo_sql: false
  echo_pool: false
  pool_size: 10 # 0 means no limit
  max_overflow: 10 # pool_size + max_overflow = max number of pools allowed
  pool_recycle: 10800 # 3 hours, -1 means no timeout
  pool_timeout: 30 # 30 seconds
  select_limit: 100
  max_select_limit: 100000
