services:
  db:
    image: postgres:16.6-bookworm
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      PG_COLOR: ${PG_COLOR:-auto}
      POSTGRES_INITDB_ARGS: "${POSTGRES_INITDB_ARGS:--E UTF8 --locale=en_US.UTF-8}"
      POSTGRES_USER: ${FOT_DB_USERNAME:-fot_admin}
      POSTGRES_PASSWORD: "${FOT_DB_PASSWORD:-FOT_DB_PASSWORD123}"
      POSTGRES_DB: ${FOT_DB_DATABASE:-fot_db}
    volumes:
      - "db-data:/var/lib/postgresql/data"
    tty: true

  api:
    image: bybatkhuu/rest.fastapi-orm-template:latest
    build:
      context: .
    depends_on:
      - db
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Asia/Seoul}
      FOT_DB_HOST: ${FOT_DB_HOST:-db}
      FOT_DB_USERNAME: ${FOT_DB_USERNAME:-fot_admin}
      FOT_DB_PASSWORD: "${FOT_DB_PASSWORD:-FOT_DB_PASSWORD123}"
      FOT_DB_DATABASE: ${FOT_DB_DATABASE:-fot_db}
      FOT_API_PORT: ${FOT_API_PORT:-8000}
    env_file:
      - path: .env
        required: false
    volumes:
      - "api-logs:${FOT_API_LOGS_DIR:-/var/log/rest.fastapi-orm-template}"
      - "api-data:${FOT_API_DATA_DIR:-/var/lib/rest.fastapi-orm-template}"
    ports:
      - "${FOT_API_PORT:-8000}:${FOT_API_PORT:-8000}"
    tty: true


volumes:
  db-data:
  api-logs:
  api-data:
