version: "3.8"

services:
  db:
    image: postgres:14.9-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${FOT_DB_USERNAME:-fot_user}
      POSTGRES_PASSWORD: "${FOT_DB_PASSWORD:-fot_password1}"
      POSTGRES_DB: ${FOT_DB_DATABASE:-fot_db}
    volumes:
      - "db-data:/var/lib/postgresql/data"

  api:
    image: bybatkhuu/fastapi-orm-template:latest
    build:
      context: .
    depends_on:
      - db
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Asia/Seoul}
      FOT_APP_PORT: ${FOT_APP_PORT:-8000}
    volumes:
      - "api-logs:/var/log/fastapi-orm-template"
      - "api-data:/var/lib/fastapi-orm-template"
    ports:
      - "${FOT_APP_PORT:-8000}:${FOT_APP_PORT:-8000}"
    tty: true

volumes:
  db-data:
  api-logs:
  api-data:
