version: "3.8"

services:
  db:
    image: postgres:14.9-bookworm
    hostname: ${FOT_DB_HOST:-db}
    restart: unless-stopped
    environment:
      PGPORT: ${FOT_DB_PORT:-5432}
      POSTGRES_USER: ${FOT_DB_USERNAME:-fot_user}
      POSTGRES_PASSWORD: "${FOT_DB_PASSWORD:-fot_password1}"
      POSTGRES_DB: ${FOT_DB_DATABASE:-fot_db}
    volumes:
      - "./volumes/storage/postgresql/data:/var/lib/postgresql/data"

  api:
    image: bybatkhuu/fastapi-orm-template:latest
    build:
      context: .
    depends_on:
      - db
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-Asia/Seoul}
      ENV: ${ENV:-local}
      FOT_APP_PORT: ${FOT_APP_PORT:-8000}
    volumes:
      - "./volumes/storage/fastapi-orm-template/logs:/var/log/fastapi-orm-template"
      - "./volumes/storage/fastapi-orm-template/data:/var/lib/fastapi-orm-template"
    ports:
      - "${FOT_APP_PORT:-8000}:${FOT_APP_PORT:-8000}"
    tty: true
