version: "3.8"

services:
  api:
    image: bybatkhuu/fastapi-orm-template:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Asia/Seoul}
      - TERM=${TERM:-xterm}
      - ENV=${ENV:-local}
      - FOT_PORT=${FOT_PORT:-8000}
    volumes:
      - "./volumes/storage/fastapi-orm-template/data:/var/lib/fastapi-orm-template"
      - "./volumes/storage/fastapi-orm-template/logs:/var/log/fastapi-orm-template"
    ports:
      - "${FOT_PORT:-8000}:${FOT_PORT:-8000}"
    tty: true
