version: "3.8"

services:
  api:
    image: bybatkhuu/fastapi-template:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Asia/Seoul}
      - TERM=${TERM:-xterm}
      - ENV=${ENV:-local}
      - FASTAPI_TEMPLATE_PORT=${FASTAPI_TEMPLATE_PORT:-8000}
    volumes:
      - "./volumes/storage/fastapi-template/data:/var/lib/fastapi-template"
      - "./volumes/storage/fastapi-template/logs:/var/log/fastapi-template"
    ports:
      - "${FASTAPI_TEMPLATE_PORT:-8000}:${FASTAPI_TEMPLATE_PORT:-8000}"
    tty: true
