version: "3.8"

services:
  api:
    # env_file:
    #   - .env
    environment:
      - DEBUG=${DEBUG:-false}
      # - FOT_DATA_DIR=/var/lib/fastapi-orm-template
      # - FOT_LOGS_DIR=/var/log/fastapi-orm-template
    volumes:
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./app:/app/fastapi-orm-template"
      - "./volumes/.vscode-server:/home/fot-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "sleep 1 && uvicorn main:app --host=0.0.0.0 --port='${FOT_PORT:-8000}' --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log --reload --reload-include='*.yml' --reload-include='*.yaml' --reload-include='*.json'"]
