name: 4. Update Changelog

on:
  # workflow_run:
  #   workflows: ["3. Create Release"]
  #   types:
  #     - completed
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build_publish:
    name: Update Changelog
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update changelog
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          ./scripts/changelog.sh -c -p
