"""Initial.

Revision ID: fad2357c10db
Revises:
Create Date: 2023-11-27 02:20:39.837497+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fad2357c10db"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    ## Functions
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_updated_at()
        RETURNS trigger
        AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END
        $$
        LANGUAGE plpgsql;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    _table_name = "fot_task"
    op.create_table(
        _table_name,
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("point", sa.Integer(), server_default=sa.text("70"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fot_task")),
    )
    op.create_index(
        "idx_created_at_desc", "fot_task", [sa.text("created_at DESC")], unique=False
    )
    # ### end Alembic commands ###

    ## Triggers
    op.execute(
        f"""
        CREATE OR REPLACE TRIGGER tr_{_table_name}_updated_at
        BEFORE UPDATE ON {_table_name}
        FOR EACH ROW
        EXECUTE PROCEDURE fn_updated_at();
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fot_task")
    # ### end Alembic commands ###
