services:
  db:
    # volumes:
    #   - "./volumes/storage/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
    #   - "./volumes/storage/postgresql/logs:/var/log/postgresql"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    ports:
      - "${FOT_DB_PORT:-5432}:${FOT_DB_PORT:-5432}"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${FOT_DB_USERNAME:-fot_admin} -d ${FOT_DB_DATABASE:-fot_db}"]
    #   start_period: 15s
    #   start_interval: 1s
    #   interval: 1m
    #   timeout: 5s
    #   retries: 3

  # db-gui:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-fot_admin@example.com}
  #     PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD:-FOT_PGADMIN_PASSWORD123}"
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "db-gui-data:/var/lib/pgadmin"
  #   deploy:
  #     replicas: 0
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 512M
  #   ports:
  #     - "${PGADMIN_PORT:-8080}:80"

  api:
    # depends_on:
    #   db:
    #     condition: service_healthy
    environment:
      FOT_DB_HOST: db
    volumes:
      - "./volumes/storage/rest.fastapi-orm-template/logs:${FOT_API_LOGS_DIR:-/var/log/rest.fastapi-orm-template}"
      - "./volumes/storage/rest.fastapi-orm-template/data:${FOT_API_DATA_DIR:-/var/lib/rest.fastapi-orm-template}"
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./src:/app/rest.fastapi-orm-template"
      - "./volumes/.vscode-server:/home/fot-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "uvicorn main:app --host=0.0.0.0 --port=${FOT_API_PORT:-8000} --no-access-log --no-server-header --proxy-headers --forwarded-allow-ips='*' --reload --reload-include='*.yml' --reload-include='.env'"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${FOT_API_PORT:-8000}/api/v${FOT_API_VERSION:-1}/ping"]
    #   start_period: 30s
    #   start_interval: 1s
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3


# volumes:
#   db-gui-data:
