env: local
debug: false
tz: "Asia/Seoul"

app:
  name: "FastAPI ORM Template"
  slug: "fastapi-orm-template"
  bind_host: "0.0.0.0"
  port: 8000
  gzip_min_size: 1024 # Bytes (1KB)
  behind_proxy: true
  behind_cf_proxy: true
  allowed_hosts: ["*"]
  forwarded_allow_ips: ["*"]
  cors:
    allow_origins: ["*"]
    allow_origin_regex: null
    allow_headers: ["*"]
    allow_methods:
      ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "CONNECT"]
    allow_credentials: false
    expose_headers: []
    max_age: 600 # Seconds (10 minutes)
  dev:
    reload: false
    reload_includes: ["*.json", "*.yml", "*.yaml"]
    reload_excludes:
      [
        "*.pyc",
        "*.pyo",
        "*.pyd",
        "__pycache__",
        "*.git",
        ".github",
        "*.svn",
        "*.hg",
        "*.log",
      ]
