env: local
debug: false

app:
  name: "FastAPI Template"
  bind_host: "0.0.0.0"
  port: 8000
  tz: "Asia/Seoul"
  api_version: "v1"
  api_prefix: "/api/{api_version}"
  behind_proxy: true
  behind_cf_proxy: true
  gzip_min_size: 1024 # Bytes (1KB)
  data_dir: "/var/lib/fastapi-template"
