db:
  dialect: "postgresql"
  driver: "psycopg"
  dsn_url: "postgresql+psycopg://fot_user:fot_password1@localhost:5432/fot_db"
  # read_dsn_url: "postgresql+psycopg://fot_user:fot_password1@localhost:5432/fot_db"
  table_prefix: "fot_"
  max_try_connect: 3
  wait_seconds_try_connect: 10
  echo_sql: false
  echo_pool: false
  pool_size: 10 # 0 means no limit
  max_overflow: 10 # pool_size + max_overflow = max number of pools allowed
  pool_recycle: 10800 # 3 hours, -1 means no timeout
  pool_timeout: 30 # 30 seconds
  select_limit: 100
  max_select_limit: 100000
