dev:
  reload: false
  reload_includes: ["*.json", "*.yml", "*.yaml"]
  reload_excludes:
    [
      "*.pyc",
      "*.pyo",
      "*.pyd",
      "__pycache__",
      "*.git",
      ".github",
      "*.svn",
      "*.hg",
      "*.log",
    ]
