docs:
  enabled: true
  openapi_url: "{api_prefix}/openapi.json"
  docs_url: "{api_prefix}/docs"
  redoc_url: "{api_prefix}/redoc"
  swagger_ui_oauth2_redirect_url: "{api_prefix}/docs/oauth2-redirect"
  summary: "This is a FastAPI Template project."
  description: ""
  terms_of_service: "https://example.com/terms"
  contact:
    name: "Support Team"
    email: "support@example.com"
    url: "https://example.com/contact"
  license_info:
    name: "MIT License"
    identifier: "MIT"
    url: "https://opensource.org/licenses/MIT"
  openapi_tags:
    - name: "Utils"
      description: "Useful utility endpoints."
  swagger_ui_parameters:
    syntaxHighlight.theme: nord
