secure:
  allowed_hosts: ["*"]
  forwarded_allow_ips: ["*"]
  cors:
    allow_origins: ["*"]
    allow_origin_regex: null
    allow_headers: ["*"]
    allow_methods:
      ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "CONNECT"]
    allow_credentials: false
    expose_headers: []
    max_age: 600 # Seconds (10 minutes)
