services:
  # db:
  #   volumes:
  #     - "./volumes/storage/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
  #     - "db-logs:/var/log/postgresql"
  #   deploy:
  #     replicas: 0
  #     resources:
  #       limits:
  #         cpus: "1.0"
  #         memory: 1G
  #   ports:
  #     - "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}DB_PORT:-5432}:{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}DB_PORT:-5432}"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}DB_USERNAME:-{{cookiecutter.project_abbr}}_admin} -d {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}DB_DATABASE:-{{cookiecutter.project_abbr}}_db}"]
  #     start_period: 15s
  #     start_interval: 1s
  #     interval: 1m
  #     timeout: 5s
  #     retries: 3

  # db-gui:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}DB_GUI_EMAIL:-{{cookiecutter.project_abbr}}_admin@example.com}
  #     PGADMIN_DEFAULT_PASSWORD: "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}DB_GUI_PASSWORD:-{{cookiecutter.env_prefix}}DB_GUI_PASSWORD123}"
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "db-gui-data:/var/lib/pgadmin"
  #   deploy:
  #     replicas: 0
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 512M
  #   ports:
  #     - "${PGADMIN_PORT:-8080}:80"

  api:
    image: {{cookiecutter.docker_registry}}/{{cookiecutter.docker_repo_name}}:{{cookiecutter.version}}
    # volumes:
    #   - "api-vscode-server:/home/{{cookiecutter.project_abbr}}-user/.vscode-server"
    # depends_on:
    #   db:
    #     condition: service_healthy
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "uvicorn main:app --host=0.0.0.0 --port={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_PORT:-8000} --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_PORT:-8000}/api/v{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_VERSION:-1}/ping"]
    #   start_period: 30s
    #   start_interval: 1s
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3


# volumes:
#   db-logs:
#   db-gui-data:
#   api-vscode-server:
