name: 2. Build and Publish

on:
  workflow_run:
    branches:
      - main
    workflows: ["1. Bump Version"]
    types:
      - completed
  push:
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches:
  #     - main

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Lint dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set version
        run: echo "_VERSION=$(./scripts/get-version.sh)" >> ${GITHUB_ENV}
      -
        name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fastapi-template:cache-latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-template:test
      -
        name: Test docker image
        run: |
          docker run --rm -dt -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-template:test
          sleep 3
          curl -s http://localhost:8000/api/v1/health | grep "OK"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fastapi-template:cache-latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fastapi-template:cache-latest,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-template:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-template:${{ env._VERSION }}
          push: true
      -
        name: Trigger release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run 3.create-release.yml -r v$(./scripts/get-version.sh)
