name: 3. Create Release

on:
  # workflow_run:
  #   workflows: ["2. Build and Publish"]
  #   types:
  #     - completed
  #   branches:
  #     - main
  workflow_dispatch:

env:
  _WORKFLOW_STATE: active

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create v$(./scripts/get-version.sh) --generate-notes
      - name: Check Workflow
        id: check_workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          _WORKFLOW_STATE=$(gh api repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/workflows/4.update-changelog.yml | jq -r '.state')
          echo "_WORKFLOW_STATE=${_WORKFLOW_STATE}" >> ${GITHUB_ENV}
      - name: Trigger Changelog
        if: ${{ env._WORKFLOW_STATE == 'active' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run 4.update-changelog.yml
