version: "3.8"

services:
  db:
    # volumes:
    #   - "./volumes/storage/postgresql/conf.d:/etc/postgresql"
    #   - "./volumes/storage/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    #   - "./volumes/storage/postgresql/logs:/var/log/postgresql"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    ports:
        - "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}DB_PORT:-5432}:{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}DB_PORT:-5432}"

  # db-gui:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-{{cookiecutter.project_abbr}}_user@{{cookiecutter.domain}}}
  #     PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD:-{{cookiecutter.project_abbr}}_password1}"
  #   volumes:
  #     - "db-gui-data:/var/lib/pgadmin"
  #   deploy:
  #     replicas: 0
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 512M
  #   ports:
  #     - "${PGADMIN_PORT:-8080}:80"

  api:
    image: {{cookiecutter.docker_registry}}/{{cookiecutter.project_slug}}:latest-gpu
    runtime: nvidia
    # env_file:
    #   - .env
    environment:
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-all}
      DEBUG: ${DEBUG:-false}
      # {{cookiecutter.env_prefix}}APP_LOGS_DIR: "/var/log/{{cookiecutter.project_slug}}"
      # {{cookiecutter.env_prefix}}APP_DATA_DIR: "/var/lib/{{cookiecutter.project_slug}}"
    volumes:
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./app:/app/{{cookiecutter.project_slug}}"
      - "./volumes/.vscode-server:/home/{{cookiecutter.project_abbr}}-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "sleep 1 && uvicorn main:app --host=0.0.0.0 --port={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_PORT:-8000} --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log --reload --reload-include='*.yml' --reload-include='*.yaml' --reload-include='*.json'"]

# volumes:
#   db-gui-data:
