version: "3.8"

services:
  api:
    image: {{cookiecutter.docker_registry}}/{{cookiecutter.project_slug}}:latest-gpu
    runtime: nvidia
    # env_file:
    #   - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-all}
      - DEBUG=${DEBUG:-false}
      # - {{cookiecutter.env_prefix}}DATA_DIR=/var/lib/{{cookiecutter.project_slug}}
      # - {{cookiecutter.env_prefix}}LOGS_DIR=/var/log/{{cookiecutter.project_slug}}
    volumes:
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./app:/app/{{cookiecutter.project_slug}}"
      - "./volumes/.vscode-server:/home/{{cookiecutter.project_abbr}}-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "sleep 1 && uvicorn main:app --host=0.0.0.0 --port='{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}PORT:-8000}' --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log --reload --reload-include='*.yml' --reload-include='*.yaml' --reload-include='*.json'"]
